// Code generated by mockery v2.24.0. DO NOT EDIT.

package network

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockeryMockWebsocket is an autogenerated mock type for the Websocket type
type MockeryMockWebsocket struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockeryMockWebsocket) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadMessage provides a mock function with given fields:
func (_m *MockeryMockWebsocket) ReadMessage() (int, []byte, error) {
	ret := _m.Called()

	var r0 int
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func() (int, []byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() []byte); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetWriteDeadline provides a mock function with given fields: t
func (_m *MockeryMockWebsocket) SetWriteDeadline(t time.Time) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteControl provides a mock function with given fields: messageType, data, deadline
func (_m *MockeryMockWebsocket) WriteControl(messageType int, data []byte, deadline time.Time) error {
	ret := _m.Called(messageType, data, deadline)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte, time.Time) error); ok {
		r0 = rf(messageType, data, deadline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteMessage provides a mock function with given fields: messageType, data
func (_m *MockeryMockWebsocket) WriteMessage(messageType int, data []byte) error {
	ret := _m.Called(messageType, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte) error); ok {
		r0 = rf(messageType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockWebsocket interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockeryMockWebsocket creates a new instance of MockeryMockWebsocket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockeryMockWebsocket(t mockConstructorTestingTNewMockWebsocket) *MockeryMockWebsocket {
	mock := &MockeryMockWebsocket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
